### ISSUE TITLE
Can I train yolov1 by using single GPU?

### ISSUE THREAD

**Issue by PeterKim1** [yakhyo/YOLOv1-pt#3]
Hi. Thanks for your great works.

I have one GPU, so I can use single GPU training strategy.

But in https://github.com/yakhyo/yolov1-pytorch/blob/main/main.py#L63, I think your codes use multi GPU strategy.

How can I train using single GPU?

Thanks.

**Comment by yakhyo** [comment]
Hi @PeterKim1, it should work for single GPU also
